#Func('glTexParameterfv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTexParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTexImage1D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLint, 'border', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glTexImage2D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLint, 'border', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glReadPixels', [Param(tGLint, 'x', None), Param(tGLint, 'y', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetBooleanv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetDoublev', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetFloatv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetIntegerv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetString', [Param(tGLenum, 'name', None)], tPointer)
#Func('glGetTexImage', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetTexParameterfv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTexParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTexLevelParameterfv', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTexLevelParameteriv', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glDrawElements', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None)], None)
#Func('glTexSubImage1D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLsizei, 'width', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glTexSubImage2D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glDeleteTextures', [Param(tGLsizei, 'n', None), Param(tPointer, 'textures', None)], None)
#Func('glGenTextures', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'textures', None)], None)
#Func('glDrawRangeElements', [Param(tGLenum, 'mode', None), Param(tGLuint, 'start', None), Param(tGLuint, 'end', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None)], None)
#Func('glTexImage3D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLint, 'border', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glTexSubImage3D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glCompressedTexImage3D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLint, 'border', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexImage2D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLint, 'border', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexImage1D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLint, 'border', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexSubImage3D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexSubImage2D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexSubImage1D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLsizei, 'width', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glGetCompressedTexImage', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tMutablePointer, 'img', None)], None)
#Func('glMultiDrawArrays', [Param(tGLenum, 'mode', None), Param(tPointer, 'first', None), Param(tPointer, 'count', None), Param(tGLsizei, 'drawcount', None)], None)
#Func('glMultiDrawElements', [Param(tGLenum, 'mode', None), Param(tPointer, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'drawcount', None)], None)
#Func('glPointParameterfv', [Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glPointParameteriv', [Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glGenQueries', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'ids', None)], None)
#Func('glDeleteQueries', [Param(tGLsizei, 'n', None), Param(tPointer, 'ids', None)], None)
#Func('glGetQueryiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetQueryObjectiv', [Param(tGLuint, 'id', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetQueryObjectuiv', [Param(tGLuint, 'id', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glDeleteBuffers', [Param(tGLsizei, 'n', None), Param(tPointer, 'buffers', None)], None)
#Func('glGenBuffers', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'buffers', None)], None)
Func('glBufferData', [Param(tGLenum, 'target', None), Param(tGLsizeiptr, 'size', None), Param(tData('size'), 'data', None), Param(tGLenum, 'usage', None)], None)
Func('glBufferSubData', [Param(tGLenum, 'target', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tData('size'), 'data', None)], None)
#Func('glGetBufferSubData', [Param(tGLenum, 'target', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tMutablePointer, 'data', None)], None)
#Func('glMapBuffer', [Param(tGLenum, 'target', None), Param(tGLenum, 'access', None)], tPointer)
#Func('glGetBufferParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetBufferPointerv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glDrawBuffers', [Param(tGLsizei, 'n', None), Param(tPointer, 'bufs', None)], None)
#Func('glGetActiveAttrib', [Param(tGLuint, 'program', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'size', None), Param(tMutablePointer, 'type', None), Param(tMutableString, 'name', None)], None)
#Func('glGetActiveUniform', [Param(tGLuint, 'program', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'size', None), Param(tMutablePointer, 'type', None), Param(tMutableString, 'name', None)], None)
#Func('glGetAttachedShaders', [Param(tGLuint, 'program', None), Param(tGLsizei, 'maxCount', None), Param(tMutablePointer, 'count', None), Param(tMutablePointer, 'shaders', None)], None)
#Func('glGetProgramiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetProgramInfoLog', [Param(tGLuint, 'program', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'infoLog', None)], None)
#Func('glGetShaderiv', [Param(tGLuint, 'shader', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetShaderInfoLog', [Param(tGLuint, 'shader', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'infoLog', None)], None)
#Func('glGetShaderSource', [Param(tGLuint, 'shader', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'source', None)], None)
#Func('glGetUniformfv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetUniformiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribdv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribfv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribPointerv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'pointer', None)], None)
#Func('glShaderSource', [Param(tGLuint, 'shader', None), Param(tGLsizei, 'count', None), Param(tPointer, 'string', None), Param(tPointer, 'length', None)], None)
Func('glUniform1fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count')], None)
Func('glUniform2fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*2')], None)
Func('glUniform3fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*3')], None)
Func('glUniform4fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*4')], None)
Func('glUniform1iv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count')], None)
Func('glUniform2iv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*2')], None)
Func('glUniform3iv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*3')], None)
Func('glUniform4iv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*4')], None)
#Func('glUniformMatrix2fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix3fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix4fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glVertexAttrib1dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib1fv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib1sv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib2dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib2fv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib2sv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib3dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib3fv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib3sv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4Nbv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4Niv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4Nsv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4Nubv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4Nuiv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4Nusv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4bv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4fv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4iv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4sv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4ubv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4uiv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttrib4usv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribPointer', [Param(tGLuint, 'index', None), Param(tGLint, 'size', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tGLsizei, 'stride', None), Param(tPointer, 'pointer', None)], None)
#Func('glUniformMatrix2x3fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix3x2fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix2x4fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix4x2fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix3x4fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix4x3fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glGetBooleani_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetIntegeri_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glTransformFeedbackVaryings', [Param(tGLuint, 'program', None), Param(tGLsizei, 'count', None), Param(tPointer, 'varyings', None), Param(tGLenum, 'bufferMode', None)], None)
#Func('glGetTransformFeedbackVarying', [Param(tGLuint, 'program', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'size', None), Param(tMutablePointer, 'type', None), Param(tMutableString, 'name', None)], None)
#Func('glVertexAttribIPointer', [Param(tGLuint, 'index', None), Param(tGLint, 'size', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'stride', None), Param(tPointer, 'pointer', None)], None)
#Func('glGetVertexAttribIiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribIuiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glVertexAttribI1iv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI2iv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI3iv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI4iv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI1uiv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI2uiv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI3uiv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI4uiv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI4bv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI4sv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI4ubv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribI4usv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glGetUniformuiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glUniform1uiv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glUniform2uiv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glUniform3uiv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glUniform4uiv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glTexParameterIiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTexParameterIuiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glGetTexParameterIiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTexParameterIuiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glClearBufferiv', [Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glClearBufferuiv', [Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glClearBufferfv', [Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glGetStringi', [Param(tGLenum, 'name', None), Param(tGLuint, 'index', None)], tPointer)
#Func('glDeleteRenderbuffers', [Param(tGLsizei, 'n', None), Param(tPointer, 'renderbuffers', None)], None)
#Func('glGenRenderbuffers', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'renderbuffers', None)], None)
#Func('glGetRenderbufferParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glDeleteFramebuffers', [Param(tGLsizei, 'n', None), Param(tPointer, 'framebuffers', None)], None)
#Func('glGenFramebuffers', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'framebuffers', None)], None)
#Func('glGetFramebufferAttachmentParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'attachment', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glMapBufferRange', [Param(tGLenum, 'target', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'length', None), Param(tGLbitfield, 'access', None)], tPointer)
#Func('glDeleteVertexArrays', [Param(tGLsizei, 'n', None), Param(tPointer, 'arrays', None)], None)
#Func('glGenVertexArrays', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'arrays', None)], None)
#Func('glDrawElementsInstanced', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'instancecount', None)], None)
#Func('glGetUniformIndices', [Param(tGLuint, 'program', None), Param(tGLsizei, 'uniformCount', None), Param(tPointer, 'uniformNames', None), Param(tMutablePointer, 'uniformIndices', None)], None)
#Func('glGetActiveUniformsiv', [Param(tGLuint, 'program', None), Param(tGLsizei, 'uniformCount', None), Param(tPointer, 'uniformIndices', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetActiveUniformName', [Param(tGLuint, 'program', None), Param(tGLuint, 'uniformIndex', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'uniformName', None)], None)
#Func('glGetActiveUniformBlockiv', [Param(tGLuint, 'program', None), Param(tGLuint, 'uniformBlockIndex', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetActiveUniformBlockName', [Param(tGLuint, 'program', None), Param(tGLuint, 'uniformBlockIndex', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'uniformBlockName', None)], None)
#Func('glGetIntegeri_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glDrawElementsBaseVertex', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLint, 'basevertex', None)], None)
#Func('glDrawRangeElementsBaseVertex', [Param(tGLenum, 'mode', None), Param(tGLuint, 'start', None), Param(tGLuint, 'end', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLint, 'basevertex', None)], None)
#Func('glDrawElementsInstancedBaseVertex', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'instancecount', None), Param(tGLint, 'basevertex', None)], None)
#Func('glMultiDrawElementsBaseVertex', [Param(tGLenum, 'mode', None), Param(tPointer, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'drawcount', None), Param(tPointer, 'basevertex', None)], None)
#Func('glGetInteger64v', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetSynciv', [Param(tGLsync, 'sync', None), Param(tGLenum, 'pname', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'values', None)], None)
#Func('glGetInteger64i_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetBufferParameteri64v', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetMultisamplefv', [Param(tGLenum, 'pname', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'val', None)], None)
#Func('glGenSamplers', [Param(tGLsizei, 'count', None), Param(tMutablePointer, 'samplers', None)], None)
#Func('glDeleteSamplers', [Param(tGLsizei, 'count', None), Param(tPointer, 'samplers', None)], None)
#Func('glSamplerParameteriv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glSamplerParameterfv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glSamplerParameterIiv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glSamplerParameterIuiv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glGetSamplerParameteriv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetSamplerParameterIiv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetSamplerParameterfv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetSamplerParameterIuiv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetQueryObjecti64v', [Param(tGLuint, 'id', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetQueryObjectui64v', [Param(tGLuint, 'id', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glVertexAttribP1uiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tPointer, 'value', None)], None)
#Func('glVertexAttribP2uiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tPointer, 'value', None)], None)
#Func('glVertexAttribP3uiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tPointer, 'value', None)], None)
#Func('glVertexAttribP4uiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tPointer, 'value', None)], None)
#Func('glDrawArraysIndirect', [Param(tGLenum, 'mode', None), Param(tPointer, 'indirect', None)], None)
#Func('glDrawElementsIndirect', [Param(tGLenum, 'mode', None), Param(tGLenum, 'type', None), Param(tPointer, 'indirect', None)], None)
#Func('glUniform1dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glUniform2dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glUniform3dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glUniform4dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix2dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix3dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix4dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix2x3dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix2x4dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix3x2dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix3x4dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix4x2dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glUniformMatrix4x3dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glGetUniformdv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetActiveSubroutineUniformiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'shadertype', None), Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'values', None)], None)
#Func('glGetActiveSubroutineUniformName', [Param(tGLuint, 'program', None), Param(tGLenum, 'shadertype', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufsize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'name', None)], None)
#Func('glGetActiveSubroutineName', [Param(tGLuint, 'program', None), Param(tGLenum, 'shadertype', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufsize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'name', None)], None)
#Func('glUniformSubroutinesuiv', [Param(tGLenum, 'shadertype', None), Param(tGLsizei, 'count', None), Param(tPointer, 'indices', None)], None)
#Func('glGetUniformSubroutineuiv', [Param(tGLenum, 'shadertype', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetProgramStageiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'shadertype', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'values', None)], None)
#Func('glPatchParameterfv', [Param(tGLenum, 'pname', None), Param(tPointer, 'values', None)], None)
#Func('glDeleteTransformFeedbacks', [Param(tGLsizei, 'n', None), Param(tPointer, 'ids', None)], None)
#Func('glGenTransformFeedbacks', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'ids', None)], None)
#Func('glGetQueryIndexediv', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glShaderBinary', [Param(tGLsizei, 'count', None), Param(tPointer, 'shaders', None), Param(tGLenum, 'binaryformat', None), Param(tPointer, 'binary', None), Param(tGLsizei, 'length', None)], None)
#Func('glGetShaderPrecisionFormat', [Param(tGLenum, 'shadertype', None), Param(tGLenum, 'precisiontype', None), Param(tMutablePointer, 'range', None), Param(tMutablePointer, 'precision', None)], None)
#Func('glGetProgramBinary', [Param(tGLuint, 'program', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'binaryFormat', None), Param(tMutablePointer, 'binary', None)], None)
#Func('glProgramBinary', [Param(tGLuint, 'program', None), Param(tGLenum, 'binaryFormat', None), Param(tPointer, 'binary', None), Param(tGLsizei, 'length', None)], None)
#Func('glCreateShaderProgramv', [Param(tGLenum, 'type', None), Param(tGLsizei, 'count', None), Param(tPointer, 'strings', None)], tGLuint)
#Func('glDeleteProgramPipelines', [Param(tGLsizei, 'n', None), Param(tPointer, 'pipelines', None)], None)
#Func('glGenProgramPipelines', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'pipelines', None)], None)
#Func('glGetProgramPipelineiv', [Param(tGLuint, 'pipeline', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glProgramUniform1iv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform1fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform1dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform1uiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform2iv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform2fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform2dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform2uiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform3iv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform3fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform3dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform3uiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform4iv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform4fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform4dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniform4uiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix2fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix3fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix4fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix2dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix3dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix4dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix2x3fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix3x2fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix2x4fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix4x2fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix3x4fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix4x3fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix2x3dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix3x2dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix2x4dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix4x2dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix3x4dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glProgramUniformMatrix4x3dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tPointer, 'value', None)], None)
#Func('glGetProgramPipelineInfoLog', [Param(tGLuint, 'pipeline', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'infoLog', None)], None)
#Func('glVertexAttribL1dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribL2dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribL3dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribL4dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribLPointer', [Param(tGLuint, 'index', None), Param(tGLint, 'size', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'stride', None), Param(tPointer, 'pointer', None)], None)
#Func('glGetVertexAttribLdv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glViewportArrayv', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'v', None)], None)
#Func('glViewportIndexedfv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glScissorArrayv', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'v', None)], None)
#Func('glScissorIndexedv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glDepthRangeArrayv', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'v', None)], None)
#Func('glGetFloati_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetDoublei_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glDrawElementsInstancedBaseInstance', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'instancecount', None), Param(tGLuint, 'baseinstance', None)], None)
#Func('glDrawElementsInstancedBaseVertexBaseInstance', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'instancecount', None), Param(tGLint, 'basevertex', None), Param(tGLuint, 'baseinstance', None)], None)
#Func('glGetInternalformativ', [Param(tGLenum, 'target', None), Param(tGLenum, 'internalformat', None), Param(tGLenum, 'pname', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetActiveAtomicCounterBufferiv', [Param(tGLuint, 'program', None), Param(tGLuint, 'bufferIndex', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glClearBufferData', [Param(tGLenum, 'target', None), Param(tGLenum, 'internalformat', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glClearBufferSubData', [Param(tGLenum, 'target', None), Param(tGLenum, 'internalformat', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glGetFramebufferParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetInternalformati64v', [Param(tGLenum, 'target', None), Param(tGLenum, 'internalformat', None), Param(tGLenum, 'pname', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glInvalidateFramebuffer', [Param(tGLenum, 'target', None), Param(tGLsizei, 'numAttachments', None), Param(tPointer, 'attachments', None)], None)
#Func('glInvalidateSubFramebuffer', [Param(tGLenum, 'target', None), Param(tGLsizei, 'numAttachments', None), Param(tPointer, 'attachments', None), Param(tGLint, 'x', None), Param(tGLint, 'y', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None)], None)
#Func('glMultiDrawArraysIndirect', [Param(tGLenum, 'mode', None), Param(tPointer, 'indirect', None), Param(tGLsizei, 'drawcount', None), Param(tGLsizei, 'stride', None)], None)
#Func('glMultiDrawElementsIndirect', [Param(tGLenum, 'mode', None), Param(tGLenum, 'type', None), Param(tPointer, 'indirect', None), Param(tGLsizei, 'drawcount', None), Param(tGLsizei, 'stride', None)], None)
#Func('glGetProgramInterfaceiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'programInterface', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetProgramResourceName', [Param(tGLuint, 'program', None), Param(tGLenum, 'programInterface', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'name', None)], None)
#Func('glGetProgramResourceiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'programInterface', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'propCount', None), Param(tPointer, 'props', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'params', None)], None)
#Func('glDebugMessageControl', [Param(tGLenum, 'source', None), Param(tGLenum, 'type', None), Param(tGLenum, 'severity', None), Param(tGLsizei, 'count', None), Param(tPointer, 'ids', None), Param(tGLboolean, 'enabled', None)], None)
#Func('glDebugMessageCallback', [Param(tGLDEBUGPROC, 'callback', None), Param(tPointer, 'userParam', None)], None)
#Func('glGetDebugMessageLog', [Param(tGLuint, 'count', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'sources', None), Param(tMutablePointer, 'types', None), Param(tMutablePointer, 'ids', None), Param(tMutablePointer, 'severities', None), Param(tMutablePointer, 'lengths', None), Param(tMutableString, 'messageLog', None)], tGLuint)
#Func('glGetObjectLabel', [Param(tGLenum, 'identifier', None), Param(tGLuint, 'name', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'label', None)], None)
#Func('glObjectPtrLabel', [Param(tPointer, 'ptr', None), Param(tGLsizei, 'length', None), Param(tString, 'label', None)], None)
#Func('glGetObjectPtrLabel', [Param(tPointer, 'ptr', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'label', None)], None)
#Func('glGetPointerv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetPointerv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glBufferStorage', [Param(tGLenum, 'target', None), Param(tGLsizeiptr, 'size', None), Param(tPointer, 'data', None), Param(tGLbitfield, 'flags', None)], None)
#Func('glClearTexImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glClearTexSubImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glBindBuffersBase', [Param(tGLenum, 'target', None), Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'buffers', None)], None)
#Func('glBindBuffersRange', [Param(tGLenum, 'target', None), Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'buffers', None), Param(tPointer, 'offsets', None), Param(tPointer, 'sizes', None)], None)
#Func('glBindTextures', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'textures', None)], None)
#Func('glBindSamplers', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'samplers', None)], None)
#Func('glBindImageTextures', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'textures', None)], None)
#Func('glBindVertexBuffers', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'buffers', None), Param(tPointer, 'offsets', None), Param(tPointer, 'strides', None)], None)
#Func('glCreateTransformFeedbacks', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'ids', None)], None)
#Func('glGetTransformFeedbackiv', [Param(tGLuint, 'xfb', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetTransformFeedbacki_v', [Param(tGLuint, 'xfb', None), Param(tGLenum, 'pname', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetTransformFeedbacki64_v', [Param(tGLuint, 'xfb', None), Param(tGLenum, 'pname', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'param', None)], None)
#Func('glCreateBuffers', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'buffers', None)], None)
#Func('glNamedBufferStorage', [Param(tGLuint, 'buffer', None), Param(tGLsizeiptr, 'size', None), Param(tPointer, 'data', None), Param(tGLbitfield, 'flags', None)], None)
#Func('glNamedBufferData', [Param(tGLuint, 'buffer', None), Param(tGLsizeiptr, 'size', None), Param(tPointer, 'data', None), Param(tGLenum, 'usage', None)], None)
#Func('glNamedBufferSubData', [Param(tGLuint, 'buffer', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tPointer, 'data', None)], None)
#Func('glClearNamedBufferData', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'internalformat', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glClearNamedBufferSubData', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'internalformat', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glMapNamedBuffer', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'access', None)], tPointer)
#Func('glMapNamedBufferRange', [Param(tGLuint, 'buffer', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'length', None), Param(tGLbitfield, 'access', None)], tPointer)
#Func('glGetNamedBufferParameteriv', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetNamedBufferParameteri64v', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetNamedBufferPointerv', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetNamedBufferSubData', [Param(tGLuint, 'buffer', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tMutablePointer, 'data', None)], None)
#Func('glCreateFramebuffers', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'framebuffers', None)], None)
#Func('glNamedFramebufferDrawBuffers', [Param(tGLuint, 'framebuffer', None), Param(tGLsizei, 'n', None), Param(tPointer, 'bufs', None)], None)
#Func('glInvalidateNamedFramebufferData', [Param(tGLuint, 'framebuffer', None), Param(tGLsizei, 'numAttachments', None), Param(tPointer, 'attachments', None)], None)
#Func('glInvalidateNamedFramebufferSubData', [Param(tGLuint, 'framebuffer', None), Param(tGLsizei, 'numAttachments', None), Param(tPointer, 'attachments', None), Param(tGLint, 'x', None), Param(tGLint, 'y', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None)], None)
#Func('glClearNamedFramebufferiv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glClearNamedFramebufferuiv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glClearNamedFramebufferfv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glGetNamedFramebufferParameteriv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetNamedFramebufferAttachmentParameteriv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'attachment', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glCreateRenderbuffers', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'renderbuffers', None)], None)
#Func('glGetNamedRenderbufferParameteriv', [Param(tGLuint, 'renderbuffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glCreateTextures', [Param(tGLenum, 'target', None), Param(tGLsizei, 'n', None), Param(tMutablePointer, 'textures', None)], None)
#Func('glTextureSubImage1D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLsizei, 'width', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glTextureSubImage2D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glTextureSubImage3D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glCompressedTextureSubImage1D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLsizei, 'width', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTextureSubImage2D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTextureSubImage3D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glTextureParameterfv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glTextureParameterIiv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTextureParameterIuiv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTextureParameteriv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glGetTextureImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetCompressedTextureImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetTextureLevelParameterfv', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureLevelParameteriv', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureParameterfv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureParameterIiv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureParameterIuiv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureParameteriv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glCreateVertexArrays', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'arrays', None)], None)
#Func('glVertexArrayVertexBuffers', [Param(tGLuint, 'vaobj', None), Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'buffers', None), Param(tPointer, 'offsets', None), Param(tPointer, 'strides', None)], None)
#Func('glGetVertexArrayiv', [Param(tGLuint, 'vaobj', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetVertexArrayIndexediv', [Param(tGLuint, 'vaobj', None), Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetVertexArrayIndexed64iv', [Param(tGLuint, 'vaobj', None), Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glCreateSamplers', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'samplers', None)], None)
#Func('glCreateProgramPipelines', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'pipelines', None)], None)
#Func('glCreateQueries', [Param(tGLenum, 'target', None), Param(tGLsizei, 'n', None), Param(tMutablePointer, 'ids', None)], None)
#Func('glGetTextureSubImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetCompressedTextureSubImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetnCompressedTexImage', [Param(tGLenum, 'target', None), Param(tGLint, 'lod', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetnTexImage', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetnUniformdv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetnUniformfv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetnUniformiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetnUniformuiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glReadnPixels', [Param(tGLint, 'x', None), Param(tGLint, 'y', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'data', None)], None)
