#Func('glTexParameterfv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTexParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
Func('glTexImage1D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLint, 'border', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tData('get_texel_size(format, type)*width'), 'pixels', None)], None)
#TODO: Support NULL
Func('glTexImage2D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLint, 'border', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tData('get_texel_size(format, type)*width*height'), 'pixels', None)], None)
#Func('glReadPixels', [Param(tGLint, 'x', None), Param(tGLint, 'y', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetBooleanv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetDoublev', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetFloatv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetIntegerv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetString', [Param(tGLenum, 'name', None)], tPointer)
#Func('glGetTexImage', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetTexParameterfv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTexParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTexLevelParameterfv', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTexLevelParameteriv', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glTexSubImage1D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLsizei, 'width', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tData('get_texel_size(format, type)*width'), 'pixels', None)], None)
Func('glTexSubImage2D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tData('get_texel_size(format, type)*width*height'), 'pixels', None)], None)
Func('glDeleteTextures', [Param(tGLsizei, 'n', None), Param(tGLuint, 'textures', 'n')], None)
Func('glGenTextures', [Param(tGLsizei, 'n', None), Param(tGLuint, 'textures', 'n')], None)
#Func('glDrawRangeElements', [Param(tGLenum, 'mode', None), Param(tGLuint, 'start', None), Param(tGLuint, 'end', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None)], None)
Func('glTexImage3D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLint, 'border', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tData('get_texel_size(format, type)*width*height*depth'), 'pixels', None)], None)
Func('glTexSubImage3D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tData('get_texel_size(format, type)*width*height*depth'), 'pixels', None)], None)
#Func('glCompressedTexImage3D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLint, 'border', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexImage2D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLint, 'border', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexImage1D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'internalformat', None), Param(tGLsizei, 'width', None), Param(tGLint, 'border', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexSubImage3D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexSubImage2D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTexSubImage1D', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLsizei, 'width', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glGetCompressedTexImage', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tMutablePointer, 'img', None)], None)
Func('glMultiDrawArrays', [Param(tGLenum, 'mode', None), Param(tGLint, 'first', 'drawcount'), Param(tGLsizei, 'count', 'drawcount'), Param(tGLsizei, 'drawcount', None)], None)
Func('glMultiDrawElements', [Param(tGLenum, 'mode', None), Param(tPointer, 'count', 'drawcount'), Param(tGLenum, 'type', None), Param(tPointer, 'indices', 'drawcount'), Param(tGLsizei, 'drawcount', None)], None)
#Func('glPointParameterfv', [Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glPointParameteriv', [Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
Func('glGenQueries', [Param(tGLsizei, 'n', None), Param(tGLuint, 'ids', 'n')], None)
Func('glDeleteQueries', [Param(tGLsizei, 'n', None), Param(tGLuint, 'ids', 'n')], None)
#Func('glGetQueryiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetQueryObjectiv', [Param(tGLuint, 'id', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetQueryObjectuiv', [Param(tGLuint, 'id', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glDeleteBuffers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'buffers', 'n')], None)
Func('glGenBuffers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'buffers', 'n')], None)
Func('glBufferData', [Param(tGLenum, 'target', None), Param(tGLsizeiptr, 'size', None), Param(tData('size'), 'data', None), Param(tGLenum, 'usage', None)], None)
Func('glBufferSubData', [Param(tGLenum, 'target', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tData('size'), 'data', None)], None)
#Func('glGetBufferSubData', [Param(tGLenum, 'target', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tMutablePointer, 'data', None)], None)
#Func('glMapBuffer', [Param(tGLenum, 'target', None), Param(tGLenum, 'access', None)], tPointer)
#Func('glGetBufferParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetBufferPointerv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glDrawBuffers', [Param(tGLsizei, 'n', None), Param(tGLenum, 'bufs', 'n')], None)
#Func('glGetActiveAttrib', [Param(tGLuint, 'program', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'size', None), Param(tMutablePointer, 'type', None), Param(tMutableString, 'name', None)], None)
#Func('glGetActiveUniform', [Param(tGLuint, 'program', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'size', None), Param(tMutablePointer, 'type', None), Param(tMutableString, 'name', None)], None)
#Func('glGetAttachedShaders', [Param(tGLuint, 'program', None), Param(tGLsizei, 'maxCount', None), Param(tMutablePointer, 'count', None), Param(tMutablePointer, 'shaders', None)], None)
#Func('glGetProgramiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetProgramInfoLog', [Param(tGLuint, 'program', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'infoLog', None)], None)
#Func('glGetShaderiv', [Param(tGLuint, 'shader', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetShaderInfoLog', [Param(tGLuint, 'shader', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'infoLog', None)], None)
#Func('glGetShaderSource', [Param(tGLuint, 'shader', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'source', None)], None)
#Func('glGetUniformfv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetUniformiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribdv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribfv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribPointerv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'pointer', None)], None)
#Func('glShaderSource', [Param(tGLuint, 'shader', None), Param(tGLsizei, 'count', None), Param(tPointer, 'string', None), Param(tPointer, 'length', None)], None)
Func('glUniform1fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count')], None)
Func('glUniform2fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*2')], None)
Func('glUniform3fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*3')], None)
Func('glUniform4fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*4')], None)
Func('glUniform1iv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count')], None)
Func('glUniform2iv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*2')], None)
Func('glUniform3iv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*3')], None)
Func('glUniform4iv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*4')], None)
Func('glUniformMatrix2fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', '4*count')], None)
Func('glUniformMatrix3fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', '9*count')], None)
Func('glUniformMatrix4fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', '16*count')], None)
Func('glVertexAttrib1dv', [Param(tGLuint, 'index', None), Param(tGLdouble, 'v', 1)], None)
Func('glVertexAttrib1fv', [Param(tGLuint, 'index', None), Param(tGLfloat, 'v', 1)], None)
Func('glVertexAttrib1sv', [Param(tGLuint, 'index', None), Param(tGLshort, 'v', 1)], None)
Func('glVertexAttrib2dv', [Param(tGLuint, 'index', None), Param(tGLdouble, 'v', 2)], None)
Func('glVertexAttrib2fv', [Param(tGLuint, 'index', None), Param(tGLfloat, 'v', 2)], None)
Func('glVertexAttrib2sv', [Param(tGLuint, 'index', None), Param(tGLshort, 'v', 2)], None)
Func('glVertexAttrib3dv', [Param(tGLuint, 'index', None), Param(tGLdouble, 'v', 3)], None)
Func('glVertexAttrib3fv', [Param(tGLuint, 'index', None), Param(tGLfloat, 'v', 3)], None)
Func('glVertexAttrib3sv', [Param(tGLuint, 'index', None), Param(tGLshort, 'v', 3)], None)
Func('glVertexAttrib4Nbv', [Param(tGLuint, 'index', None), Param(tGLbyte, 'v', 4)], None)
Func('glVertexAttrib4Niv', [Param(tGLuint, 'index', None), Param(tGLint, 'v', 4)], None)
Func('glVertexAttrib4Nsv', [Param(tGLuint, 'index', None), Param(tGLshort, 'v', 4)], None)
Func('glVertexAttrib4Nubv', [Param(tGLuint, 'index', None), Param(tGLubyte, 'v', 4)], None)
Func('glVertexAttrib4Nuiv', [Param(tGLuint, 'index', None), Param(tGLuint, 'v', 4)], None)
Func('glVertexAttrib4Nusv', [Param(tGLuint, 'index', None), Param(tGLushort, 'v', 4)], None)
Func('glVertexAttrib4bv', [Param(tGLuint, 'index', None), Param(tGLbyte, 'v', 4)], None)
Func('glVertexAttrib4dv', [Param(tGLuint, 'index', None), Param(tGLdouble, 'v', 4)], None)
Func('glVertexAttrib4fv', [Param(tGLuint, 'index', None), Param(tGLfloat, 'v', 4)], None)
Func('glVertexAttrib4iv', [Param(tGLuint, 'index', None), Param(tGLint, 'v', 4)], None)
Func('glVertexAttrib4sv', [Param(tGLuint, 'index', None), Param(tGLshort, 'v', 4)], None)
Func('glVertexAttrib4ubv', [Param(tGLuint, 'index', None), Param(tGLubyte, 'v', 4)], None)
Func('glVertexAttrib4uiv', [Param(tGLuint, 'index', None), Param(tGLuint, 'v', 4)], None)
Func('glVertexAttrib4usv', [Param(tGLuint, 'index', None), Param(tGLushort, 'v', )], None)
#Func('glVertexAttribPointer', [Param(tGLuint, 'index', None), Param(tGLint, 'size', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tGLsizei, 'stride', None), Param(tPointer, 'pointer', None)], None)
Func('glUniformMatrix2x3fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*6')], None)
Func('glUniformMatrix3x2fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*6')], None)
Func('glUniformMatrix2x4fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*8')], None)
Func('glUniformMatrix4x2fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*8')], None)
Func('glUniformMatrix3x4fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*12')], None)
Func('glUniformMatrix4x3fv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*12')], None)
#Func('glGetBooleani_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetIntegeri_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glTransformFeedbackVaryings', [Param(tGLuint, 'program', None), Param(tGLsizei, 'count', None), Param(tPointer, 'varyings', None), Param(tGLenum, 'bufferMode', None)], None)
#Func('glGetTransformFeedbackVarying', [Param(tGLuint, 'program', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'size', None), Param(tMutablePointer, 'type', None), Param(tMutableString, 'name', None)], None)
#Func('glVertexAttribIPointer', [Param(tGLuint, 'index', None), Param(tGLint, 'size', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'stride', None), Param(tPointer, 'pointer', None)], None)
#Func('glGetVertexAttribIiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetVertexAttribIuiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glVertexAttribI1iv', [Param(tGLuint, 'index', None), Param(tGLint, 'v', 1)], None)
Func('glVertexAttribI2iv', [Param(tGLuint, 'index', None), Param(tGLint, 'v', 2)], None)
Func('glVertexAttribI3iv', [Param(tGLuint, 'index', None), Param(tGLint, 'v', 3)], None)
Func('glVertexAttribI4iv', [Param(tGLuint, 'index', None), Param(tGLint, 'v', 4)], None)
Func('glVertexAttribI1uiv', [Param(tGLuint, 'index', None), Param(tGLuint, 'v', 1)], None)
Func('glVertexAttribI2uiv', [Param(tGLuint, 'index', None), Param(tGLuint, 'v', 2)], None)
Func('glVertexAttribI3uiv', [Param(tGLuint, 'index', None), Param(tGLuint, 'v', 3)], None)
Func('glVertexAttribI4uiv', [Param(tGLuint, 'index', None), Param(tGLuint, 'v', 4)], None)
Func('glVertexAttribI4bv', [Param(tGLuint, 'index', None), Param(tGLbyte, 'v', 4)], None)
Func('glVertexAttribI4sv', [Param(tGLuint, 'index', None), Param(tGLbyte, 'v', 4)], None)
Func('glVertexAttribI4ubv', [Param(tGLuint, 'index', None), Param(tGLubyte, 'v', 4)], None)
Func('glVertexAttribI4usv', [Param(tGLuint, 'index', None), Param(tGLubyte, 'v', 4)], None)
#Func('glGetUniformuiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
Func('glUniform1uiv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'value', 'count')], None)
Func('glUniform2uiv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', 'count*2')], None)
Func('glUniform3uiv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', 'count*3')], None)
Func('glUniform4uiv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tPointer, 'value', 'count*4')], None)
#Func('glTexParameterIiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTexParameterIuiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glGetTexParameterIiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTexParameterIuiv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glClearBufferiv', [Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glClearBufferuiv', [Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glClearBufferfv', [Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glGetStringi', [Param(tGLenum, 'name', None), Param(tGLuint, 'index', None)], tPointer)
Func('glDeleteRenderbuffers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'renderbuffers', 'n')], None)
Func('glGenRenderbuffers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'renderbuffers', 'n')], None)
#Func('glGetRenderbufferParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glDeleteFramebuffers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'framebuffers', 'n')], None)
Func('glGenFramebuffers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'framebuffers', 'n')], None)
#Func('glGetFramebufferAttachmentParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'attachment', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glMapBufferRange', [Param(tGLenum, 'target', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'length', None), Param(tGLbitfield, 'access', None)], tPointer)
Func('glDeleteVertexArrays', [Param(tGLsizei, 'n', None), Param(tGLuint, 'arrays', 'n')], None)
Func('glGenVertexArrays', [Param(tGLsizei, 'n', None), Param(tGLuint, 'arrays', 'n')], None)
#Func('glDrawElementsInstanced', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'instancecount', None)], None)
#Func('glGetUniformIndices', [Param(tGLuint, 'program', None), Param(tGLsizei, 'uniformCount', None), Param(tPointer, 'uniformNames', None), Param(tMutablePointer, 'uniformIndices', None)], None)
#Func('glGetActiveUniformsiv', [Param(tGLuint, 'program', None), Param(tGLsizei, 'uniformCount', None), Param(tPointer, 'uniformIndices', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetActiveUniformName', [Param(tGLuint, 'program', None), Param(tGLuint, 'uniformIndex', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'uniformName', None)], None)
#Func('glGetActiveUniformBlockiv', [Param(tGLuint, 'program', None), Param(tGLuint, 'uniformBlockIndex', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetActiveUniformBlockName', [Param(tGLuint, 'program', None), Param(tGLuint, 'uniformBlockIndex', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'uniformBlockName', None)], None)
#Func('glGetIntegeri_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glDrawElementsBaseVertex', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLint, 'basevertex', None)], None)
#Func('glDrawRangeElementsBaseVertex', [Param(tGLenum, 'mode', None), Param(tGLuint, 'start', None), Param(tGLuint, 'end', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLint, 'basevertex', None)], None)
#Func('glDrawElementsInstancedBaseVertex', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'instancecount', None), Param(tGLint, 'basevertex', None)], None)
Func('glMultiDrawElementsBaseVertex', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', 'drawcount'), Param(tGLenum, 'type', None), Param(tPointer, 'indices', 'drawcount'), Param(tGLsizei, 'drawcount', None), Param(tPointer, 'basevertex', 'drawcount')], None)
#Func('glGetInteger64v', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetSynciv', [Param(tGLsync, 'sync', None), Param(tGLenum, 'pname', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'values', None)], None)
#Func('glGetInteger64i_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetBufferParameteri64v', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetMultisamplefv', [Param(tGLenum, 'pname', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'val', None)], None)
Func('glGenSamplers', [Param(tGLsizei, 'count', None), Param(tGLuint, 'samplers', 'count')], None)
Func('glDeleteSamplers', [Param(tGLsizei, 'count', None), Param(tGLuint, 'samplers', 'count')], None)
#Func('glSamplerParameteriv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glSamplerParameterfv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glSamplerParameterIiv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glSamplerParameterIuiv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glGetSamplerParameteriv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetSamplerParameterIiv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetSamplerParameterfv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetSamplerParameterIuiv', [Param(tGLuint, 'sampler', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetQueryObjecti64v', [Param(tGLuint, 'id', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetQueryObjectui64v', [Param(tGLuint, 'id', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glVertexAttribP1uiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tPointer, 'value', None)], None)
#Func('glVertexAttribP2uiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tPointer, 'value', None)], None)
#Func('glVertexAttribP3uiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tPointer, 'value', None)], None)
#Func('glVertexAttribP4uiv', [Param(tGLuint, 'index', None), Param(tGLenum, 'type', None), Param(tGLboolean, 'normalized', None), Param(tPointer, 'value', None)], None)
#Func('glDrawArraysIndirect', [Param(tGLenum, 'mode', None), Param(tPointer, 'indirect', None)], None)
#Func('glDrawElementsIndirect', [Param(tGLenum, 'mode', None), Param(tGLenum, 'type', None), Param(tPointer, 'indirect', None)], None)
Func('glUniform1dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLdouble, 'value', 'count')], None)
Func('glUniform2dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLdouble, 'value', 'count*2')], None)
Func('glUniform3dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLdouble, 'value', 'count*3')], None)
Func('glUniform4dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLdouble, 'value', 'count*4')], None)
Func('glUniformMatrix2dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '4*count')], None)
Func('glUniformMatrix3dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '9*count')], None)
Func('glUniformMatrix4dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '16*count')], None)
Func('glUniformMatrix2x3dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '6*count')], None)
Func('glUniformMatrix2x4dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '8*count')], None)
Func('glUniformMatrix3x2dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '6*count')], None)
Func('glUniformMatrix3x4dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '12*count')], None)
Func('glUniformMatrix4x2dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '8*count')], None)
Func('glUniformMatrix4x3dv', [Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', '12*count')], None)
#Func('glGetUniformdv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetActiveSubroutineUniformiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'shadertype', None), Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'values', None)], None)
#Func('glGetActiveSubroutineUniformName', [Param(tGLuint, 'program', None), Param(tGLenum, 'shadertype', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufsize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'name', None)], None)
#Func('glGetActiveSubroutineName', [Param(tGLuint, 'program', None), Param(tGLenum, 'shadertype', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufsize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'name', None)], None)
#Func('glUniformSubroutinesuiv', [Param(tGLenum, 'shadertype', None), Param(tGLsizei, 'count', None), Param(tPointer, 'indices', None)], None)
#Func('glGetUniformSubroutineuiv', [Param(tGLenum, 'shadertype', None), Param(tGLint, 'location', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetProgramStageiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'shadertype', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'values', None)], None)
#Func('glPatchParameterfv', [Param(tGLenum, 'pname', None), Param(tPointer, 'values', None)], None)
Func('glDeleteTransformFeedbacks', [Param(tGLsizei, 'n', None), Param(tGLuint, 'ids', 'n')], None)
Func('glGenTransformFeedbacks', [Param(tGLsizei, 'n', None), Param(tGLuint, 'ids', 'n')], None)
#Func('glGetQueryIndexediv', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glShaderBinary', [Param(tGLsizei, 'count', None), Param(tPointer, 'shaders', None), Param(tGLenum, 'binaryformat', None), Param(tPointer, 'binary', None), Param(tGLsizei, 'length', None)], None)
#Func('glGetShaderPrecisionFormat', [Param(tGLenum, 'shadertype', None), Param(tGLenum, 'precisiontype', None), Param(tMutablePointer, 'range', None), Param(tMutablePointer, 'precision', None)], None)
#Func('glGetProgramBinary', [Param(tGLuint, 'program', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'binaryFormat', None), Param(tMutablePointer, 'binary', None)], None)
#Func('glProgramBinary', [Param(tGLuint, 'program', None), Param(tGLenum, 'binaryFormat', None), Param(tPointer, 'binary', None), Param(tGLsizei, 'length', None)], None)
#Func('glCreateShaderProgramv', [Param(tGLenum, 'type', None), Param(tGLsizei, 'count', None), Param(tPointer, 'strings', None)], tGLuint)
Func('glDeleteProgramPipelines', [Param(tGLsizei, 'n', None), Param(tGLuint, 'pipelines', 'n')], None)
Func('glGenProgramPipelines', [Param(tGLsizei, 'n', None), Param(tGLuint, 'pipelines', 'n')], None)
#Func('glGetProgramPipelineiv', [Param(tGLuint, 'pipeline', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glProgramUniform1iv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count')], None)
Func('glProgramUniform1fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count')], None)
Func('glProgramUniform1dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLdouble, 'value', 'count')], None)
Func('glProgramUniform1uiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'value', 'count')], None)
Func('glProgramUniform2iv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*2')], None)
Func('glProgramUniform2fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*2')], None)
Func('glProgramUniform2dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLdouble, 'value', 'count*2')], None)
Func('glProgramUniform2uiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'value', 'count*2')], None)
Func('glProgramUniform3iv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*3')], None)
Func('glProgramUniform3fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*3')], None)
Func('glProgramUniform3dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLdouble, 'value', 'count*3')], None)
Func('glProgramUniform3uiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'value', 'count*3')], None)
Func('glProgramUniform4iv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLint, 'value', 'count*4')], None)
Func('glProgramUniform4fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLfloat, 'value', 'count*4')], None)
Func('glProgramUniform4dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLdouble, 'value', 'count*4')], None)
Func('glProgramUniform4uiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'value', 'count*4')], None)
Func('glProgramUniformMatrix2fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*4')], None)
Func('glProgramUniformMatrix3fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*9')], None)
Func('glProgramUniformMatrix4fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*16')], None)
Func('glProgramUniformMatrix2dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*4')], None)
Func('glProgramUniformMatrix3dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*9')], None)
Func('glProgramUniformMatrix4dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*16')], None)
Func('glProgramUniformMatrix2x3fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*6')], None)
Func('glProgramUniformMatrix3x2fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*6')], None)
Func('glProgramUniformMatrix2x4fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*8')], None)
Func('glProgramUniformMatrix4x2fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*8')], None)
Func('glProgramUniformMatrix3x4fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*12')], None)
Func('glProgramUniformMatrix4x3fv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLfloat, 'value', 'count*12')], None)
Func('glProgramUniformMatrix2x3dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*6')], None)
Func('glProgramUniformMatrix3x2dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*6')], None)
Func('glProgramUniformMatrix2x4dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*8')], None)
Func('glProgramUniformMatrix4x2dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*8')], None)
Func('glProgramUniformMatrix3x4dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*12')], None)
Func('glProgramUniformMatrix4x3dv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'count', None), Param(tGLboolean, 'transpose', None), Param(tGLdouble, 'value', 'count*12')], None)
#Func('glGetProgramPipelineInfoLog', [Param(tGLuint, 'pipeline', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'infoLog', None)], None)
#Func('glVertexAttribL1dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribL2dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribL3dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribL4dv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glVertexAttribLPointer', [Param(tGLuint, 'index', None), Param(tGLint, 'size', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'stride', None), Param(tPointer, 'pointer', None)], None)
#Func('glGetVertexAttribLdv', [Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glViewportArrayv', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'v', None)], None)
#Func('glViewportIndexedfv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glScissorArrayv', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'v', None)], None)
#Func('glScissorIndexedv', [Param(tGLuint, 'index', None), Param(tPointer, 'v', None)], None)
#Func('glDepthRangeArrayv', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'v', None)], None)
#Func('glGetFloati_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glGetDoublei_v', [Param(tGLenum, 'target', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'data', None)], None)
#Func('glDrawElementsInstancedBaseInstance', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'instancecount', None), Param(tGLuint, 'baseinstance', None)], None)
#Func('glDrawElementsInstancedBaseVertexBaseInstance', [Param(tGLenum, 'mode', None), Param(tGLsizei, 'count', None), Param(tGLenum, 'type', None), Param(tPointer, 'indices', None), Param(tGLsizei, 'instancecount', None), Param(tGLint, 'basevertex', None), Param(tGLuint, 'baseinstance', None)], None)
#Func('glGetInternalformativ', [Param(tGLenum, 'target', None), Param(tGLenum, 'internalformat', None), Param(tGLenum, 'pname', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetActiveAtomicCounterBufferiv', [Param(tGLuint, 'program', None), Param(tGLuint, 'bufferIndex', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glClearBufferData', [Param(tGLenum, 'target', None), Param(tGLenum, 'internalformat', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glClearBufferSubData', [Param(tGLenum, 'target', None), Param(tGLenum, 'internalformat', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glGetFramebufferParameteriv', [Param(tGLenum, 'target', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetInternalformati64v', [Param(tGLenum, 'target', None), Param(tGLenum, 'internalformat', None), Param(tGLenum, 'pname', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glInvalidateFramebuffer', [Param(tGLenum, 'target', None), Param(tGLsizei, 'numAttachments', None), Param(tPointer, 'attachments', None)], None)
#Func('glInvalidateSubFramebuffer', [Param(tGLenum, 'target', None), Param(tGLsizei, 'numAttachments', None), Param(tPointer, 'attachments', None), Param(tGLint, 'x', None), Param(tGLint, 'y', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None)], None)
#Func('glMultiDrawArraysIndirect', [Param(tGLenum, 'mode', None), Param(tPointer, 'indirect', None), Param(tGLsizei, 'drawcount', None), Param(tGLsizei, 'stride', None)], None)
#Func('glMultiDrawElementsIndirect', [Param(tGLenum, 'mode', None), Param(tGLenum, 'type', None), Param(tPointer, 'indirect', None), Param(tGLsizei, 'drawcount', None), Param(tGLsizei, 'stride', None)], None)
#Func('glGetProgramInterfaceiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'programInterface', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetProgramResourceName', [Param(tGLuint, 'program', None), Param(tGLenum, 'programInterface', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'name', None)], None)
#Func('glGetProgramResourceiv', [Param(tGLuint, 'program', None), Param(tGLenum, 'programInterface', None), Param(tGLuint, 'index', None), Param(tGLsizei, 'propCount', None), Param(tPointer, 'props', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutablePointer, 'params', None)], None)
#Func('glDebugMessageControl', [Param(tGLenum, 'source', None), Param(tGLenum, 'type', None), Param(tGLenum, 'severity', None), Param(tGLsizei, 'count', None), Param(tPointer, 'ids', None), Param(tGLboolean, 'enabled', None)], None)
#Func('glDebugMessageCallback', [Param(tGLDEBUGPROC, 'callback', None), Param(tPointer, 'userParam', None)], None)
#Func('glGetDebugMessageLog', [Param(tGLuint, 'count', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'sources', None), Param(tMutablePointer, 'types', None), Param(tMutablePointer, 'ids', None), Param(tMutablePointer, 'severities', None), Param(tMutablePointer, 'lengths', None), Param(tMutableString, 'messageLog', None)], tGLuint)
#Func('glGetObjectLabel', [Param(tGLenum, 'identifier', None), Param(tGLuint, 'name', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'label', None)], None)
#Func('glObjectPtrLabel', [Param(tPointer, 'ptr', None), Param(tGLsizei, 'length', None), Param(tString, 'label', None)], None)
#Func('glGetObjectPtrLabel', [Param(tPointer, 'ptr', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'length', None), Param(tMutableString, 'label', None)], None)
#Func('glGetPointerv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetPointerv', [Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glBufferStorage', [Param(tGLenum, 'target', None), Param(tGLsizeiptr, 'size', None), Param(tPointer, 'data', None), Param(tGLbitfield, 'flags', None)], None)
#Func('glClearTexImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glClearTexSubImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glBindBuffersBase', [Param(tGLenum, 'target', None), Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'buffers', None)], None)
#Func('glBindBuffersRange', [Param(tGLenum, 'target', None), Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tPointer, 'buffers', None), Param(tPointer, 'offsets', None), Param(tPointer, 'sizes', None)], None)
Func('glBindTextures', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'textures', 'count')], None)
Func('glBindSamplers', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'samplers', 'count')], None)
Func('glBindImageTextures', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'textures', 'count')], None)
Func('glBindVertexBuffers', [Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'buffers', 'count'), Param(tGLuintptr, 'offsets', 'count'), Param(tGLsizei, 'strides', 'count')], None)
Func('glCreateTransformFeedbacks', [Param(tGLsizei, 'n', None), Param(tGLuint, 'ids', 'n')], None)
#Func('glGetTransformFeedbackiv', [Param(tGLuint, 'xfb', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetTransformFeedbacki_v', [Param(tGLuint, 'xfb', None), Param(tGLenum, 'pname', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetTransformFeedbacki64_v', [Param(tGLuint, 'xfb', None), Param(tGLenum, 'pname', None), Param(tGLuint, 'index', None), Param(tMutablePointer, 'param', None)], None)
Func('glCreateBuffers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'buffers', 'n')], None)
#Func('glNamedBufferStorage', [Param(tGLuint, 'buffer', None), Param(tGLsizeiptr, 'size', None), Param(tPointer, 'data', None), Param(tGLbitfield, 'flags', None)], None)
Func('glNamedBufferData', [Param(tGLuint, 'buffer', None), Param(tGLsizeiptr, 'size', None), Param(tData('size'), 'data', None), Param(tGLenum, 'usage', None)], None)
Func('glNamedBufferSubData', [Param(tGLuint, 'buffer', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tData('size'), 'data', None)], None)
#Func('glClearNamedBufferData', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'internalformat', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glClearNamedBufferSubData', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'internalformat', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'data', None)], None)
#Func('glMapNamedBuffer', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'access', None)], tPointer)
#Func('glMapNamedBufferRange', [Param(tGLuint, 'buffer', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'length', None), Param(tGLbitfield, 'access', None)], tPointer)
#Func('glGetNamedBufferParameteriv', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetNamedBufferParameteri64v', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetNamedBufferPointerv', [Param(tGLuint, 'buffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetNamedBufferSubData', [Param(tGLuint, 'buffer', None), Param(tGLintptr, 'offset', None), Param(tGLsizeiptr, 'size', None), Param(tMutablePointer, 'data', None)], None)
#Func('glCreateFramebuffers', [Param(tGLsizei, 'n', None), Param(tMutablePointer, 'framebuffers', None)], None)
Func('glNamedFramebufferDrawBuffers', [Param(tGLuint, 'framebuffer', None), Param(tGLsizei, 'n', None), Param(tGLenum, 'bufs', 'n')], None)
#Func('glInvalidateNamedFramebufferData', [Param(tGLuint, 'framebuffer', None), Param(tGLsizei, 'numAttachments', None), Param(tPointer, 'attachments', None)], None)
#Func('glInvalidateNamedFramebufferSubData', [Param(tGLuint, 'framebuffer', None), Param(tGLsizei, 'numAttachments', None), Param(tPointer, 'attachments', None), Param(tGLint, 'x', None), Param(tGLint, 'y', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None)], None)
#Func('glClearNamedFramebufferiv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glClearNamedFramebufferuiv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glClearNamedFramebufferfv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'buffer', None), Param(tGLint, 'drawbuffer', None), Param(tPointer, 'value', None)], None)
#Func('glGetNamedFramebufferParameteriv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetNamedFramebufferAttachmentParameteriv', [Param(tGLuint, 'framebuffer', None), Param(tGLenum, 'attachment', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glCreateRenderbuffers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'renderbuffers', 'n')], None)
#Func('glGetNamedRenderbufferParameteriv', [Param(tGLuint, 'renderbuffer', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glCreateTextures', [Param(tGLenum, 'target', None), Param(tGLsizei, 'n', None), Param(tGLuint, 'textures', 'n')], None)
#Func('glTextureSubImage1D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLsizei, 'width', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glTextureSubImage2D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glTextureSubImage3D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tPointer, 'pixels', None)], None)
#Func('glCompressedTextureSubImage1D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLsizei, 'width', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTextureSubImage2D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glCompressedTextureSubImage3D', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLsizei, 'imageSize', None), Param(tPointer, 'data', None)], None)
#Func('glTextureParameterfv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glTextureParameterIiv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTextureParameterIuiv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tPointer, 'params', None)], None)
#Func('glTextureParameteriv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tPointer, 'param', None)], None)
#Func('glGetTextureImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetCompressedTextureImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetTextureLevelParameterfv', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureLevelParameteriv', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureParameterfv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureParameterIiv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureParameterIuiv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetTextureParameteriv', [Param(tGLuint, 'texture', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'params', None)], None)
Func('glCreateVertexArrays', [Param(tGLsizei, 'n', None), Param(tGLuint, 'arrays', 'n')], None)
Func('glVertexArrayVertexBuffers', [Param(tGLuint, 'vaobj', None), Param(tGLuint, 'first', None), Param(tGLsizei, 'count', None), Param(tGLuint, 'buffers', 'count'), Param(tGLintptr, 'offsets', 'count'), Param(tGLsizei, 'strides', 'count')], None)
#Func('glGetVertexArrayiv', [Param(tGLuint, 'vaobj', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetVertexArrayIndexediv', [Param(tGLuint, 'vaobj', None), Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
#Func('glGetVertexArrayIndexed64iv', [Param(tGLuint, 'vaobj', None), Param(tGLuint, 'index', None), Param(tGLenum, 'pname', None), Param(tMutablePointer, 'param', None)], None)
Func('glCreateSamplers', [Param(tGLsizei, 'n', None), Param(tGLuint, 'samplers', 'n')], None)
Func('glCreateProgramPipelines', [Param(tGLsizei, 'n', None), Param(tGLuint, 'pipelines', 'n')], None)
Func('glCreateQueries', [Param(tGLenum, 'target', None), Param(tGLsizei, 'n', None), Param(tGLuint, 'ids', 'n')], None)
#Func('glGetTextureSubImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetCompressedTextureSubImage', [Param(tGLuint, 'texture', None), Param(tGLint, 'level', None), Param(tGLint, 'xoffset', None), Param(tGLint, 'yoffset', None), Param(tGLint, 'zoffset', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLsizei, 'depth', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetnCompressedTexImage', [Param(tGLenum, 'target', None), Param(tGLint, 'lod', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetnTexImage', [Param(tGLenum, 'target', None), Param(tGLint, 'level', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'pixels', None)], None)
#Func('glGetnUniformdv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetnUniformfv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetnUniformiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glGetnUniformuiv', [Param(tGLuint, 'program', None), Param(tGLint, 'location', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'params', None)], None)
#Func('glReadnPixels', [Param(tGLint, 'x', None), Param(tGLint, 'y', None), Param(tGLsizei, 'width', None), Param(tGLsizei, 'height', None), Param(tGLenum, 'format', None), Param(tGLenum, 'type', None), Param(tGLsizei, 'bufSize', None), Param(tMutablePointer, 'data', None)], None)








#Func('glXGetFBConfigs', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tMutablePointer, 'nelements', None)], tPointer)
#Func('glXGetGPUIDsAMD', [Param(tunsignedint, 'maxCount', None), Param(tMutablePointer, 'ids', None)], tunsignedint)
#Func('glXQueryExtension', [Param(tMutablePointer, 'dpy', None), Param(tMutablePointer, 'errorb', None), Param(tMutablePointer, 'event', None)], tBool)
#Func('glXQueryServerString', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tint, 'name', None)], tPointer)
#Func('glXChannelRectSGIX', [Param(tMutablePointer, 'display', None), Param(tint, 'screen', None), Param(tint, 'channel', None), Param(tint, 'x', None), Param(tint, 'y', None), Param(tint, 'w', None), Param(tint, 'h', None)], tint)
#Func('glXCopyContext', [Param(tMutablePointer, 'dpy', None), Param(tGLXContext, 'src', None), Param(tGLXContext, 'dst', None), Param(tunsignedlong, 'mask', None)], None)
#Func('glXGetTransparentIndexSUN', [Param(tMutablePointer, 'dpy', None), Param(tWindow, 'overlay', None), Param(tWindow, 'underlay', None), Param(tMutablePointer, 'pTransparentIndex', None)], tStatus)
#Func('glXChooseVisual', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tMutablePointer, 'attribList', None)], tPointer)
#Func('glXReleaseVideoImageNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXPbuffer, 'pbuf', None)], tint)
#Func('glXDestroyGLXPbufferSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXPbufferSGIX, 'pbuf', None)], None)
#Func('glXGetCurrentAssociatedContextAMD', [], tGLXContext)
#Func('glXQueryContextInfoEXT', [Param(tMutablePointer, 'dpy', None), Param(tGLXContext, 'context', None), Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], tint)
#Func('glXQueryCurrentRendererIntegerMESA', [Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], tBool)
#Func('glXDestroyPbuffer', [Param(tMutablePointer, 'dpy', None), Param(tGLXPbuffer, 'pbuf', None)], None)
#Func('glXGetFBConfigAttribSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfigSGIX, 'config', None), Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], tint)
#Func('glXNamedCopyBufferSubDataNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXContext, 'readCtx', None), Param(tGLXContext, 'writeCtx', None), Param(tGLuint, 'readBuffer', None), Param(tGLuint, 'writeBuffer', None), Param(tGLintptr, 'readOffset', None), Param(tGLintptr, 'writeOffset', None), Param(tGLsizeiptr, 'size', None)], None)
#Func('glXHyperpipeAttribSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'timeSlice', None), Param(tint, 'attrib', None), Param(tint, 'size', None), Param(tMutablePointer, 'attribList', None)], tint)
#Func('glXDestroyGLXVideoSourceSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXVideoSourceSGIX, 'glxvideosource', None)], None)
#Func('glXQueryExtensionsString', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None)], tPointer)
#Func('glXSendPbufferToVideoNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXPbuffer, 'pbuf', None), Param(tint, 'iBufferType', None), Param(tMutablePointer, 'pulCounterPbuffer', None), Param(tGLboolean, 'bBlock', None)], tint)
#Func('glXDestroyWindow', [Param(tMutablePointer, 'dpy', None), Param(tGLXWindow, 'win', None)], None)
#Func('glXQueryHyperpipeAttribSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'timeSlice', None), Param(tint, 'attrib', None), Param(tint, 'size', None), Param(tMutablePointer, 'returnAttribList', None)], tint)
#Func('glXHyperpipeConfigSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'networkId', None), Param(tint, 'npipes', None), Param(tMutablePointer, 'cfg', None), Param(tMutablePointer, 'hpId', None)], tint)
#Func('glXDestroyContext', [Param(tMutablePointer, 'dpy', None), Param(tGLXContext, 'ctx', None)], None)
#Func('glXGetCurrentDisplayEXT', [], tPointer)
#Func('glXCreateContextWithConfigSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfigSGIX, 'config', None), Param(tint, 'render_type', None), Param(tGLXContext, 'share_list', None), Param(tBool, 'direct', None)], tGLXContext)
#Func('glXMakeAssociatedContextCurrentAMD', [Param(tGLXContext, 'ctx', None)], tBool)
#Func('glXMakeCurrentReadSGI', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'draw', None), Param(tGLXDrawable, 'read', None), Param(tGLXContext, 'ctx', None)], tBool)
#Func('glXBindSwapBarrierSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tint, 'barrier', None)], None)
#Func('glXFreeContextEXT', [Param(tMutablePointer, 'dpy', None), Param(tGLXContext, 'context', None)], None)
#Func('glXDestroyHyperpipeConfigSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'hpId', None)], tint)
#Func('glXWaitForSbcOML', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tint64_t, 'target_sbc', None), Param(tMutablePointer, 'ust', None), Param(tMutablePointer, 'msc', None), Param(tMutablePointer, 'sbc', None)], tBool)
#Func('glXGetSelectedEvent', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'draw', None), Param(tMutablePointer, 'event_mask', None)], None)
#Func('glXEnumerateVideoCaptureDevicesNV', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tMutablePointer, 'nelements', None)], tPointer)
#Func('glXCreateGLXPixmapMESA', [Param(tMutablePointer, 'dpy', None), Param(tMutablePointer, 'visual', None), Param(tPixmap, 'pixmap', None), Param(tColormap, 'cmap', None)], tGLXPixmap)
#Func('glXCreateWindow', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfig, 'config', None), Param(tWindow, 'win', None), Param(tPointer, 'attrib_list', None)], tGLXWindow)
#Func('glXGetCurrentDrawable', [], tGLXDrawable)
#Func('glXQueryHyperpipeBestAttribSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'timeSlice', None), Param(tint, 'attrib', None), Param(tint, 'size', None), Param(tMutablePointer, 'attribList', None), Param(tMutablePointer, 'returnAttribList', None)], tint)
Func('glXGetProcAddress', [Param(tString, 'procName', None)], t__GLXextFuncPtr)
#Func('glXCushionSGI', [Param(tMutablePointer, 'dpy', None), Param(tWindow, 'window', None), Param(tfloat, 'cushion', None)], None)
#Func('glXMakeContextCurrent', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'draw', None), Param(tGLXDrawable, 'read', None), Param(tGLXContext, 'ctx', None)], tBool)
#Func('glXSwapIntervalSGI', [Param(tint, 'interval', None)], tint)
#Func('glXBindTexImageEXT', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tint, 'buffer', None), Param(tPointer, 'attrib_list', None)], None)
#Func('glXReleaseVideoCaptureDeviceNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXVideoCaptureDeviceNV, 'device', None)], None)
#Func('glXGetCurrentContext', [], tGLXContext)
#Func('glXQueryMaxSwapGroupsNV', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tMutablePointer, 'maxGroups', None), Param(tMutablePointer, 'maxBarriers', None)], tBool)
#Func('glXQueryHyperpipeConfigSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'hpId', None), Param(tMutablePointer, 'npipes', None)], tPointer)
#Func('glXWaitVideoSyncSGI', [Param(tint, 'divisor', None), Param(tint, 'remainder', None), Param(tMutablePointer, 'count', None)], tint)
#Func('glXGetConfig', [Param(tMutablePointer, 'dpy', None), Param(tMutablePointer, 'visual', None), Param(tint, 'attrib', None), Param(tMutablePointer, 'value', None)], tint)
#Func('glXCreateGLXPbufferSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfigSGIX, 'config', None), Param(tunsignedint, 'width', None), Param(tunsignedint, 'height', None), Param(tMutablePointer, 'attrib_list', None)], tGLXPbufferSGIX)
#Func('glXQueryVideoCaptureDeviceNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXVideoCaptureDeviceNV, 'device', None), Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], tint)
#Func('glXGetVideoSyncSGI', [Param(tMutablePointer, 'count', None)], tint)
#Func('glXQueryDrawable', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'draw', None), Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], None)
#Func('glXLockVideoCaptureDeviceNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXVideoCaptureDeviceNV, 'device', None)], None)
#Func('glXGetCurrentDisplay', [], tPointer)
#Func('glXBlitContextFramebufferAMD', [Param(tGLXContext, 'dstCtx', None), Param(tGLint, 'srcX0', None), Param(tGLint, 'srcY0', None), Param(tGLint, 'srcX1', None), Param(tGLint, 'srcY1', None), Param(tGLint, 'dstX0', None), Param(tGLint, 'dstY0', None), Param(tGLint, 'dstX1', None), Param(tGLint, 'dstY1', None), Param(tGLbitfield, 'mask', None), Param(tGLenum, 'filter', None)], None)
#Func('glXGetClientString', [Param(tMutablePointer, 'dpy', None), Param(tint, 'name', None)], tPointer)
#Func('glXGetMscRateOML', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tMutablePointer, 'numerator', None), Param(tMutablePointer, 'denominator', None)], tBool)
#Func('glXGetCurrentReadDrawableSGI', [], tGLXDrawable)
#Func('glXReleaseBuffersMESA', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None)], tBool)
#Func('glXGetFBConfigAttrib', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfig, 'config', None), Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], tint)
#Func('glXDestroyGLXPixmap', [Param(tMutablePointer, 'dpy', None), Param(tGLXPixmap, 'pixmap', None)], None)
#Func('glXQueryVersion', [Param(tMutablePointer, 'dpy', None), Param(tMutablePointer, 'maj', None), Param(tMutablePointer, 'min', None)], tBool)
#Func('glXGetAGPOffsetMESA', [Param(tPointer, 'pointer', None)], tunsignedint)
#Func('glXWaitForMscOML', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tint64_t, 'target_msc', None), Param(tint64_t, 'divisor', None), Param(tint64_t, 'remainder', None), Param(tMutablePointer, 'ust', None), Param(tMutablePointer, 'msc', None), Param(tMutablePointer, 'sbc', None)], tBool)
#Func('glXQueryMaxSwapBarriersSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tMutablePointer, 'max', None)], tBool)
#Func('glXCreateGLXPixmap', [Param(tMutablePointer, 'dpy', None), Param(tMutablePointer, 'visual', None), Param(tPixmap, 'pixmap', None)], tGLXPixmap)
#Func('glXBindChannelToWindowSGIX', [Param(tMutablePointer, 'display', None), Param(tint, 'screen', None), Param(tint, 'channel', None), Param(tWindow, 'window', None)], tint)
#Func('glXChooseFBConfigSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tMutablePointer, 'attrib_list', None), Param(tMutablePointer, 'nelements', None)], tPointer)
#Func('glXSelectEventSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tunsignedlong, 'mask', None)], None)
#Func('glXGetContextGPUIDAMD', [Param(tGLXContext, 'ctx', None)], tunsignedint)
#Func('glXDestroyPixmap', [Param(tMutablePointer, 'dpy', None), Param(tGLXPixmap, 'pixmap', None)], None)
#Func('glXCreateNewContext', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfig, 'config', None), Param(tint, 'render_type', None), Param(tGLXContext, 'share_list', None), Param(tBool, 'direct', None)], tGLXContext)
#Func('glXQueryGLXPbufferSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXPbufferSGIX, 'pbuf', None), Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], tint)
#Func('glXCopySubBufferMESA', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tint, 'x', None), Param(tint, 'y', None), Param(tint, 'width', None), Param(tint, 'height', None)], None)
#Func('glXQueryFrameCountNV', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tMutablePointer, 'count', None)], tBool)
#Func('glXGetCurrentReadDrawable', [], tGLXDrawable)
#Func('glXResetFrameCountNV', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None)], tBool)
#Func('glXCreateAssociatedContextAttribsAMD', [Param(tunsignedint, 'id', None), Param(tGLXContext, 'share_context', None), Param(tPointer, 'attribList', None)], tGLXContext)
#Func('glXCreateContextAttribsARB', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfig, 'config', None), Param(tGLXContext, 'share_context', None), Param(tBool, 'direct', None), Param(tPointer, 'attrib_list', None)], tGLXContext)
#Func('glXDelayBeforeSwapNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tGLfloat, 'seconds', None)], tBool)
#Func('glXImportContextEXT', [Param(tMutablePointer, 'dpy', None), Param(tGLXContextID, 'contextID', None)], tGLXContext)
#Func('glXSelectEvent', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'draw', None), Param(tunsignedlong, 'event_mask', None)], None)
#Func('glXGetVideoInfoNV', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tGLXVideoDeviceNV, 'VideoDevice', None), Param(tMutablePointer, 'pulCounterOutputPbuffer', None), Param(tMutablePointer, 'pulCounterOutputVideo', None)], tint)
#Func('glXGetSyncValuesOML', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tMutablePointer, 'ust', None), Param(tMutablePointer, 'msc', None), Param(tMutablePointer, 'sbc', None)], tBool)
#Func('glXDeleteAssociatedContextAMD', [Param(tGLXContext, 'ctx', None)], tBool)
Func('glXGetProcAddressARB', [Param(tString, 'procName', None)], t__GLXextFuncPtr)
#Func('glXEnumerateVideoDevicesNV', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tMutablePointer, 'nelements', None)], tPointer)
#Func('glXCreateContext', [Param(tMutablePointer, 'dpy', None), Param(tMutablePointer, 'vis', None), Param(tGLXContext, 'shareList', None), Param(tBool, 'direct', None)], tGLXContext)
#Func('glXReleaseTexImageEXT', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tint, 'buffer', None)], None)
#Func('glXJoinSwapGroupNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tGLuint, 'group', None)], tBool)
#Func('glXCreateAssociatedContextAMD', [Param(tunsignedint, 'id', None), Param(tGLXContext, 'share_list', None)], tGLXContext)
#Func('glXBindHyperpipeSGIX', [Param(tMutablePointer, 'dpy', None), Param(tint, 'hpId', None)], tint)
#Func('glXGetSelectedEventSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tMutablePointer, 'mask', None)], None)
#Func('glXChooseFBConfig', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tPointer, 'attrib_list', None), Param(tMutablePointer, 'nelements', None)], tPointer)
#Func('glXIsDirect', [Param(tMutablePointer, 'dpy', None), Param(tGLXContext, 'ctx', None)], tBool)
#Func('glXReleaseVideoDeviceNV', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tGLXVideoDeviceNV, 'VideoDevice', None)], tint)
#Func('glXGetGPUInfoAMD', [Param(tunsignedint, 'id', None), Param(tint, 'property', None), Param(tGLenum, 'dataType', None), Param(tunsignedint, 'size', None), Param(tMutablePointer, 'data', None)], tint)
#Func('glXSwapBuffersMscOML', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tint64_t, 'target_msc', None), Param(tint64_t, 'divisor', None), Param(tint64_t, 'remainder', None)], tint64_t)
#Func('glXGetContextIDEXT', [Param(tGLXContext, 'context', None)], tGLXContextID)
#Func('glXJoinSwapGroupSGIX', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tGLXDrawable, 'member', None)], None)
#Func('glXQueryContext', [Param(tMutablePointer, 'dpy', None), Param(tGLXContext, 'ctx', None), Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], tint)
#Func('glXWaitGL', [], None)
#Func('glXQueryCurrentRendererStringMESA', [Param(tint, 'attribute', None)], tPointer)
#Func('glXCopyBufferSubDataNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXContext, 'readCtx', None), Param(tGLXContext, 'writeCtx', None), Param(tGLenum, 'readTarget', None), Param(tGLenum, 'writeTarget', None), Param(tGLintptr, 'readOffset', None), Param(tGLintptr, 'writeOffset', None), Param(tGLsizeiptr, 'size', None)], None)
#Func('glXSwapBuffers', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None)], None)
#Func('glXWaitX', [], None)
#Func('glXQueryHyperpipeNetworkSGIX', [Param(tMutablePointer, 'dpy', None), Param(tMutablePointer, 'npipes', None)], tPointer)
#Func('glXGetVideoDeviceNV', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tint, 'numVideoDevices', None), Param(tMutablePointer, 'pVideoDevice', None)], tint)
#Func('glXQueryChannelRectSGIX', [Param(tMutablePointer, 'display', None), Param(tint, 'screen', None), Param(tint, 'channel', None), Param(tMutablePointer, 'dx', None), Param(tMutablePointer, 'dy', None), Param(tMutablePointer, 'dw', None), Param(tMutablePointer, 'dh', None)], tint)
#Func('glXQueryChannelDeltasSGIX', [Param(tMutablePointer, 'display', None), Param(tint, 'screen', None), Param(tint, 'channel', None), Param(tMutablePointer, 'x', None), Param(tMutablePointer, 'y', None), Param(tMutablePointer, 'w', None), Param(tMutablePointer, 'h', None)], tint)
#Func('glXBindVideoDeviceNV', [Param(tMutablePointer, 'dpy', None), Param(tunsignedint, 'video_slot', None), Param(tunsignedint, 'video_device', None), Param(tPointer, 'attrib_list', None)], tint)
#Func('glXQueryRendererIntegerMESA', [Param(tMutablePointer, 'dpy', None), Param(tint, 'screen', None), Param(tint, 'renderer', None), Param(tint, 'attribute', None), Param(tMutablePointer, 'value', None)], tBool)
#Func('glXQuerySwapGroupNV', [Param(tMutablePointer, 'dpy', None), Param(tGLXDrawable, 'drawable', None), Param(tMutablePointer, 'group', None), Param(tMutablePointer, 'barrier', None)], tBool)
#Func('glXCreatePbuffer', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfig, 'config', None), Param(tPointer, 'attrib_list', None)], tGLXPbuffer)
#Func('glXUseXFont', [Param(tFont, 'font', None), Param(tint, 'first', None), Param(tint, 'count', None), Param(tint, 'list', None)], None)
#Func('glXGetVisualFromFBConfig', [Param(tMutablePointer, 'dpy', None), Param(tGLXFBConfig, 'config', None)], tPointer)
